del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\10\mask1.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\10\mask2.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\10\mask3.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\3\mask1.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\3\mask10.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\3\mask11.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\3\mask12.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\3\mask13.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\3\mask14.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\3\mask15.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\3\mask16.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\3\mask17.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\3\mask18.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\3\mask19.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\3\mask2.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\3\mask20.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\3\mask21.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\3\mask22.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\3\mask23.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\3\mask24.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\3\mask25.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\3\mask26.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\3\mask3.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\3\mask4.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\3\mask5.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\3\mask6.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\3\mask7.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\3\mask8.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\3\mask9.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\4\mask1.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\4\mask2.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\4\mask3.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\4\mask4.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\4\mask5.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\4\mask6.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\4\mask7.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\4\mask8.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\5\mask1.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\5\mask10.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\5\mask11.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\5\mask12.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\5\mask13.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\5\mask14.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\5\mask15.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\5\mask16.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\5\mask17.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\5\mask18.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\5\mask19.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\5\mask2.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\5\mask20.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\5\mask21.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\5\mask22.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\5\mask23.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\5\mask3.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\5\mask4.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\5\mask5.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\5\mask6.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\5\mask7.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\5\mask8.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\5\mask9.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\7\mask1.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\7\mask10.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\7\mask2.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\7\mask3.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\7\mask4.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\7\mask5.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\7\mask6.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\7\mask7.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\7\mask8.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\7\mask9.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\8\mask1.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\8\mask2.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\8\mask3.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\8\mask4.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\9\mask1.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\9\mask10.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\9\mask2.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\9\mask3.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\9\mask4.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\9\mask5.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\9\mask6.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\9\mask7.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\9\mask8.jpg
del D:\MTU\_Project_Grunt_Work\Labelled\sipaimages\9\mask9.jpg
